spring.application.name=dividejson
server.port=0

spring.rabbitmq.host=10.10.8.23
spring.rabbitmq.username=solatimq
spring.rabbitmq.password=Solati123*

message.queue=dividejson
queue.data=dividejsondata2
queue.list=dividejson
