spring.application.name=dividejsondata
server.port=0

spring.rabbitmq.host=10.10.8.17
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

message.queue=dividejson
queue.data=dividejsondata2
queue.list=dividejson
