spring.application.name=dividejson
server.port=8180

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=solatimq
spring.rabbitmq.password=Qpalwosk2019

message.queue=dividejson
queue.data=dividejsondata
queue.list=dividejson
