spring.application.name=dividejson
server.port=0

spring.rabbitmq.host=ab9860b0f41754820b9fab56e42e625a-1531739255.us-east-1.elb.amazonaws.com
spring.rabbitmq.username=admin
spring.rabbitmq.password=Qpalwosk2019/

message.queue=prueba

queue.data=prueba2
queue.list=prueba3

