spring.application.name=dividejsondata
server.port=0

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=solatimq
spring.rabbitmq.password=Qpalwosk2019

message.queue=dividejson
queue.data=dividejsondata
queue.list=dividejson
