spring.application.name=logs-server
#server.port=8090


config.security.oauth.client.id=frontendapp
config.security.oauth.client.secret=12345
config.security.oauth.jwt.key=algun_codigo_secreto_aeiou

eureka.client.serviceUrl.defaultZone=http://23.22.131.240:8761/eureka/
© 2021 GitHub, Inc.
