spring.application.name=send-response-email
server.port=${PORT:0}

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

spring.rabbitmq.host=10.10.8.23
spring.rabbitmq.username=Solatimq
spring.rabbitmq.password=Solati123*

queue.responseEmail=responseEmail

spring.sleuth.sampler.probability=1.0
//spring.zipkin.base-url=http://zipkin-server:9411/
