spring.application.name=zuul-server
server.port=8090


config.security.oauth.client.id=frontendapp
config.security.oauth.client.secret=12345
config.security.oauth.jwt.key=hahaha

eureka.client.serviceUrl.defaultZone=http://10.10.8.17:8761/eureka

zuul.routes.createmessage.service-id=CREATEMESSAGEQUEUE
zuul.routes.createmessage.path=/api/createmessage/**

zuul.routes.auth.service-id=authentication_planta
zuul.routes.auth.path=/api/auth/**

zuul.routes.adminfoplanta.service-id=plantatelefonica
zuul.routes.adminfoplanta.path=/api/adminfo/planta/**
#zuul.routes.adminfoplanta.sensitive-headers=Cookie,Set-Cookie

zuul.routes.clienteplanta.service-id=cliente_services_planta
zuul.routes.clienteplanta.path=/api/cliente/planta**
#zuul.routes.clienteplanta.sensitive-headers=Cookie,Set-Cookie

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon.ConnectTimeout: 9000
ribbon.ReadTimeout: 30000

spring.sleuth.sampler.probability=1.0
spring.zipkin.base-url=http://10.10.8.17:9411/
