spring.application.name=zuul-server
server.port=8090


config.security.oauth.client.id=frontendapp
config.security.oauth.client.secret=12345
config.security.oauth.jwt.key=/*5014T1#.+

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

zuul.routes.createmessage.service-id=CREATEMESSAGEQUEUE
zuul.routes.createmessage.path=/api/createmessage/**

zuul.routes.auth.service-id=connect_serviciosAutenticacion 
zuul.routes.auth.path=/api/auth/**

zuul.routes.auth2.service-id=servicio-autenticacion-movil
zuul.routes.auth2.path=/api/auth2/**

zuul.routes.backend.service-id=servicio-backend-movil
zuul.routes.backend.path=/api/backend/movil/**

zuul.routes.adminfoplanta.service-id=connect_serviciosAdminfo
zuul.routes.adminfoplanta.path=/api/adminfo/planta/**
#zuul.routes.adminfoplanta.sensitive-headers=Cookie,Set-Cookie

zuul.routes.udp.service-id=connect_serviciosUDP
zuul.routes.udp.path=/api/udp/planta/**
#zuul.routes.udp.sensitive-headers=Cookie,Set-Cookie


zuul.routes.clienteplanta.service-id=connect_serviciosCliente
zuul.routes.clienteplanta.path=/api/cliente/planta/**
#zuul.routes.clienteplanta.sensitive-headers=Cookie,Set-Cookie

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon.ConnectTimeout: 9000
ribbon.ReadTimeout: 30000

spring.sleuth.sampler.probability=1.0
spring.zipkin.base-url=http://zipkin-server:9411/
